version: 2.1

orbs:
  heroku: circleci/heroku@1.2.5

jobs:
  build:
    docker:
      - image: circleci/node:12.22.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn install

workflows:
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git:
          requires:
            - build
          filters:
            branches:
              only: master